### ISSUE TITLE
tag 131

### ISSUE THREAD

**Issue by devsnek** [mweibel/node-etf#43]
so, i'm not all too experienced with etf, but i think that 131 is a version header of some sort, not an actual tag, but i might be wrong.
```js
ParserError: Unable to read tag 131
    at Parser.uint8.tap (node_modules/erlang-term-format/index.js:509:35)
    at Parser._exec_tap (node_modules/dissolve/index.js:58:12)
    at Parser._transform (node_modules/dissolve/index.js:139:12)
    at Parser.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Parser.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:308:5)
    at Parser.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at WebSocket.ws.onmessage (etftest.js:12:42)
    at WebSocket.onMessage (node_modules/ws/lib/WebSocket.js:442:14)
```

**Comment by harshagarwal00** [comment]
This didnot work for me why is it closed?

**Comment by harshagarwal00** [comment]
Fix for anyone who comes to this page:



Issue got fixed,
https://www.erlang.org/doc/apps/erts/erl_ext_dist.html
it was a compressed ETF format so had to first truncate first 6 bytes:
buffer.slice(6)
https://www.erlang.org/doc/apps/erts/erl_ext_dist.html

then deflate it:
zlib.inflateSync(new_buffer_bin)

after that apply this library.
