### ISSUE TITLE
Im getting stuck on "ParserError: Unable to read tag 131"

### ISSUE THREAD

**Issue by harshagarwal00** [mweibel/node-etf#55]
```
ParserError: Unable to read tag 131
    at Parser.<anonymous> (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/erlang-term-format/index.js:509:35)
    at Parser._exec_tap (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/index.js:58:12)
    at Parser._transform (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/index.js:139:12)
    at Parser.Transform._read (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Parser.Transform._write (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Parser.Writable.write (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/dissolve/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at /Users/harshagarwal/elyments/elyments-chat-api/src/message/message.service.ts:76:32
    t arrayEach (/Users/harshagarwal/elyments/elyments-chat-api/node_modules/lodash/lodash.js:530:11
```
    
    
    Also this issue was raised before too: https://github.com/mweibel/node-etf/issues/43
    Not sure why its closed

**Comment by harshagarwal00** [comment]
Issue got fixed,
https://www.erlang.org/doc/apps/erts/erl_ext_dist.html
it was a compressed ETF format so had to first truncate first 6 bytes:
`buffer.slice(6)`
https://www.erlang.org/doc/apps/erts/erl_ext_dist.html

then deflate it:
zlib.inflateSync(new_buffer_bin)

after that apply this library.
